### ISSUE TITLE
Configurable snapshot count

### ISSUE THREAD

**Issue by Yamakaky** [csirac2/snazzer#25] opened 2015-12-27 17:37 UTC
It should be possible to configure how many snapshots are kept.

**Comment by csirac2** [comment] 2015-12-31 12:24
Duplicate of issue #22.

Thanks for reporting. This is a commonly requested feature, I'll get to it shortly. In the meantime I usually have something like

```
. /etc/default/snazzer && snazzer
```

This loads the `SNAZZER_` envs with the desired snapshot retention settings.

**Closed as completed by csirac2** 2015-12-31 12:24 UTC

**Comment by Yamakaky** [comment] 2015-12-31 12:45
Ok

**Comment by csirac2** [comment] 2015-12-31 13:04
Check https://github.com/csirac2/snazzer/blob/master/doc/examples/etc/default/snazzer for example envs
